name: Database Operations

on:
  push:
    branches:
      - main
  

jobs:
  db_operations:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Check and Create Database
        env:
          PGHOST: ${{ secrets.AWS_RDS_HOST }}
          PGPORT: ${{ secrets.AWS_RDS_PORT }}
          PGUSER: ${{ secrets.AWS_RDS_USER }}
          PGPASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
        run: |
          DB_EXISTS=$(psql -tAc "SELECT 1 FROM pg_database WHERE datname='moongyDB'")
          if [ -z "$DB_EXISTS" ]; then
            echo "Database moongyDB does not exist. Creating database."
            createdb moongyDB
          else
            echo "Database moongyDB already exists."
          fi

      - name: Run SQL script from file
        env:
          PGHOST: ${{ secrets.AWS_RDS_HOST }}
          PGPORT: ${{ secrets.AWS_RDS_PORT }}
          PGUSER: ${{ secrets.AWS_RDS_USER }}
          PGPASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
          PGDATABASE: ${{ secrets.AWS_RDS_DB }}
        run: |
          psql -f contact.sql
